// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-POt3vbKZQYkfo88VhL6-P_Hwlj5UfE',
    appId: '1:463695338446:web:41bc15d452f40ea13f699f',
    messagingSenderId: '463695338446',
    projectId: 'note-app-2a2fe',
    authDomain: 'note-app-2a2fe.firebaseapp.com',
    storageBucket: 'note-app-2a2fe.firebasestorage.app',
    measurementId: 'G-S0B0ZTT4JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6g-j1U9EBE6bymM0Q7rn7cTRRar6ccqM',
    appId: '1:463695338446:android:ccd1afab977b9b513f699f',
    messagingSenderId: '463695338446',
    projectId: 'note-app-2a2fe',
    storageBucket: 'note-app-2a2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndtGL7HipFRDqrH_PHWbTCvgQywEkFwE',
    appId: '1:463695338446:ios:0021da068b79091a3f699f',
    messagingSenderId: '463695338446',
    projectId: 'note-app-2a2fe',
    storageBucket: 'note-app-2a2fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndtGL7HipFRDqrH_PHWbTCvgQywEkFwE',
    appId: '1:463695338446:ios:0021da068b79091a3f699f',
    messagingSenderId: '463695338446',
    projectId: 'note-app-2a2fe',
    storageBucket: 'note-app-2a2fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-POt3vbKZQYkfo88VhL6-P_Hwlj5UfE',
    appId: '1:463695338446:web:f904328294bc954a3f699f',
    messagingSenderId: '463695338446',
    projectId: 'note-app-2a2fe',
    authDomain: 'note-app-2a2fe.firebaseapp.com',
    storageBucket: 'note-app-2a2fe.firebasestorage.app',
    measurementId: 'G-ER2WHQ93ZR',
  );
}
